timeout: 20m
steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '--tag=eu.gcr.io/ons-rasrmbs-management/ras-rm-party:$COMMIT_SHA', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['run', 'eu.gcr.io/ons-rasrmbs-management/ras-rm-party:$COMMIT_SHA', 'go', 'test']
images: ['eu.gcr.io/ons-rasrmbs-management/ras-rm-party:$COMMIT_SHA']