openapi: 3.0.2
info:
  title: RAS/RM Party Service
  description: A service for dealing with various parties (businesses, survey respondents etc and their enrolments)
  version: "2.0"

servers:
  - url: https://localhost:8081/party-api/v2
    description: The default path for Party in ras-rm-docker-dev

tags:
  - name: info
    description: Informational endpoints.
  - name: respondents
    description: Endpoints for interacting with survey respondents.
  - name: businesses
    description: Endpoints for interacting with businesses.

paths:
  /info:
    get:
      summary: Returns basic information about the service.
      description: Returns service information. If the `REPORT_DEPENDENCIES` environment variable is set to true, it will also report information on service dependencies.
      security: []
      tags:
        - info
      servers:
        - url: https://localhost:8081
          description: The /info path doesn't use the /party-api/v1 prefix
      responses:
        '200':
          description: A JSON of basic information about the service.
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: ras-rm-party
                  version:
                    type: string
                    example: "1.12.0"
        '404':
          description: The basic information about the service couldn't be retrieved. The service may be configured incorrectly.
  /respondents/{id}:
    delete:
      summary: Deletes a respondent from the service.
      description: Unenrols a respondent from all surveys then deletes their enrolment history, business associations, pending enrolments and their representation in the service. Will not delete their account from the auth service.
      tags:
        - respondents
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
            example: 34597808-ec88-4e93-af2f-228e33ff7946
      responses:
        '204':
          description: A request to delete was successfully accepted.
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/RespondentNotFoundError'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid.
      headers:
        WWW_Authenticate:
          schema:
            type: string
    RespondentNotFoundError:
      description: The respondent specified wasn't found.
      content:
        application/json:
          schema:
            type: object
            properties:
              description:
                type: string
                example: Respondent does not exist
security:
  - basicAuth: []