env: minikube
namespace: minikube

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  name: eu.gcr.io/ons-rasrmbs-management
  devRepo: eu.gcr.io/ons-rasrmbs-management
  pullPolicy: Always
  tag: latest

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name
  managedRedis: false

container:
  port: 8080
service:
  port: 80

resources:
  requests:
    memory: "128Mi"

dns:
  enabled: false
  wellKnownPort: 8080