apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    run: {{ .Chart.Name }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        env: {{ .Values.env }}
    spec:
      {{- if .Values.database.sqlProxyEnabled }}
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-proxy-credentials
            defaultMode: 0444
            items:
            - key: "credentials.json"
              path: "credentials.json"
      {{- end }}
      containers:
        {{- if .Values.database.sqlProxyEnabled }}
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.16
          command: ["/cloud_sql_proxy",
                    "-instances=$(SQL_INSTANCE_NAME)=tcp:$(DB_PORT)",
                    "-ip_address_types=PRIVATE",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
          env:
          - name: SQL_INSTANCE_NAME
            valueFrom:
              configMapKeyRef:
                name: cloudsql-proxy-config
                key: instance-connection-name
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: db-config
                key: db-port
        {{- end }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}/{{ .Chart.Name }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-server
              containerPort: {{ .Values.container.port }}
          readinessProbe:
            httpGet:
              path: /v2/info
              port: {{ .Values.container.port }}
            initialDelaySeconds: 1
            periodSeconds: 20
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /v2/info
              port: {{ .Values.container.port }}
            initialDelaySeconds: 1
            periodSeconds: 20
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          env:
          - name: DB_HOST
            {{- if .Values.database.managedPostgres }}
            valueFrom:
              secretKeyRef:
                name: db-config
                key: db-host
            {{- else }}
            value: $(POSTGRES_SERVICE_HOST)
            {{- end }}
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: db-config
                key: db-port
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-config
                key: {{ .Values.database.secrets.nameKey }}
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: {{ .Values.database.secrets.usernameKey }}
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: {{ .Values.database.secrets.passwordKey }}
          - name: SECURITY_USER_NAME
            valueFrom:
              secretKeyRef:
                name: security-credentials
                key: security-user
          - name: SECURITY_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: security-credentials
                key: security-password
          - name: DATABASE_URI
            {{- if .Values.database.sqlProxyEnabled }}
            value: "postgresql://$(DB_USERNAME):$(DB_PASSWORD)@127.0.0.1:$(DB_PORT)/$(DB_NAME)?sslmode=disable"
            {{- else }}
            value: "postgresql://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=disable"
            {{- end }}
          - name: RAS_OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: oauth-secret
                key: oauth-client-id
          - name: RAS_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: oauth-secret
                key: oauth-client-secret
          - name: RAS_CASE_SERVICE_HOST
            {{- if .Values.dns.enabled }}
            value: "http://case.{{ .Values.namespace }}.svc.cluster.local"
            {{- else }}
            value: "http://$(CASE_SERVICE_HOST)"
            {{- end }}
          - name: RAS_CASE_SERVICE_PORT
            {{- if .Values.dns.enabled }}
            value: "{{ .Values.dns.wellKnownPort }}"
            {{- else }}
            value: "$(CASE_SERVICE_PORT)"
            {{- end }}
          - name: RAS_COLLEX_SERVICE_HOST
            {{- if .Values.dns.enabled }}
            value: "http://collection-exercise.{{ .Values.namespace }}.svc.cluster.local"
            {{- else }}
            value: "http://$(COLLECTION_EXERCISE_SERVICE_HOST)"
            {{- end }}
          - name: RAS_COLLEX_SERVICE_PORT
            {{- if .Values.dns.enabled }}
            value: "{{ .Values.dns.wellKnownPort }}"
            {{- else }}
            value: "$(COLLECTION_EXERCISE_SERVICE_PORT)"
            {{- end }}
          - name: RAS_IAC_SERVICE_HOST
            {{- if .Values.dns.enabled }}
            value: "http://iac.{{ .Values.namespace }}.svc.cluster.local"
            {{- else }}
            value: "http://$(IAC_SERVICE_HOST)"
            {{- end }}
          - name: RAS_IAC_SERVICE_PORT
            {{- if .Values.dns.enabled }}
            value: "{{ .Values.dns.wellKnownPort }}"
            {{- else }}
            value: "$(IAC_SERVICE_PORT)"
            {{- end }}
          - name: PORT
            value: "{{ .Values.container.port }}"
          - name: ZIPKIN_DSN
            value: "http://$(ZIPKIN_SERVICE_HOST):$(ZIPKIN_SERVICE_PORT)/api/v1/spans"
          - name: ZIPKIN_SAMPLE_RATE
            value: "100"
          - name: SERVICE_NAME
            value: ras-rm-party
          - name: APP_VERSION
            value: {{ .Chart.AppVersion }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}