# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE: sandbox
  REGISTRY_HOSTNAME: eu.gcr.io
  HOST: ${{ secrets.GOOGLE_PROJECT_ID }}


jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCR_KEY }}
    - run: |
        gcloud auth configure-docker
    # Build and tag docker file
    - name: Build
      run: |
        docker build -t "$REGISTRY_HOSTNAME"/"$HOST"/"$IMAGE":latest .
    - name: Publish
      run: |
        docker push "$REGISTRY_HOSTNAME"/"$HOST"/"$IMAGE":latest
    - name: Helm
      run: |
        helm dep up _infra/helm/partyv2
        helm package _infra/helm/partyv2
    - name: Publish Charts
      run: |
        gsutil cp partyv2-*.tgz gs://ras-rm-artifacts/partyv2/
    - uses: actions/create-release@v1
      if: ${{ github.event.pull_request.merged }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - Some Trello board ticket link.
        draft: false
        prerelease: false
